.\" Manpage for hardinfo.
.\" https://github.com/lpereira/hardinfo/.
.TH HARDINFO "1" "July 2017" "0.6" "User Commands"
.SH NAME
\fBHardInfo\fR \- System profiler and benchmark for Linux systems.
.SH USAGE
\fBhardinfo\fR [OPTION...]
.SH DESCRIPTION
Is a system profiler and benchmark for Linux systems, that gathers information about the 
hardware and operating system, performs benchmarks, and generates reports.  
The information gathered is presented on an simple and intuitive GUI.

Information is grouped in \fIfour main groups\fR: \fBComputer\fR, \fBDevices\fR, \fBNetwork\fR, and \fBBenchmarks\fR.

The \fBComputer group\fR contains mostly information about basic software.  This includes but
is not limited to information about the operating system (kernel version, C library,
distribution, etc.), kernel modules, locale information, filesystem usage, users/groups, and
development tools.

The \fBDevices group\fR contains information about the hardware, as detected by the operating
system.  \fBHardinfo\fR is incapable of detecting hardware by itself, it merely lists what the
operating system was able to find.  This includes, but does not limit to, information about the
processor (including cache layout, known bugs, and feature flags with their explanation),
devices (such as USB, PCI, and Input devices), among other things.

The \fBNetwork group\fR lists information about network interfaces, routing table, DNS servers,
and other networking-related topics.

The \fBBenchmarks group\fR allow performing simple benchmarks to test CPU and FPU capabilities,
as well as some of the graphical user interface capabilities as well.  In previous versions, it
was possible to send the benchmark results to a central server, so it was possible to compare
the benchmarks with other \fBHardinfo\fR users; this service has been deactivated in the mean time.

\fIReports\fR can be generated either by invoking \fBHardinfo\fR with special command-line parameters
(see below), or by clicking the "Generate Report" button in the GUI.  Reports can be customized
in the GUI and saved in either HTML or plain text formats.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-r\fR, \fB\-\-generate\-report\fR
creates a report and prints to standard output
.TP
\fB\-f\fR, \fB\-\-report\-format\fR
chooses a report format (text, html)
.TP
\fB\-b\fR, \fB\-\-run\-benchmark\fR
run benchmark; requires benchmark.so to be loaded
.TP
\fB\-l\fR, \fB\-\-list\-modules\fR
lists modules
.TP
\fB\-m\fR, \fB\-\-load\-module\fR
specify module to load
.TP
\fB\-a\fR, \fB\-\-autoload\-deps\fR
automatically load module dependencies
.TP
\fB\-v\fR, \fB\-\-version\fR
shows program version and quit
.SH AUTHORS/CONTRIBUTORS
For current maintainers committing, see AUTHORS.md file and more info are at \fIhttps://github.com/lpereira/hardinfo/graphs/contributors\fR . 
More contributions are in each files source headers.
.SH COPYRIGHT
\fBHardInfo\fR its Copyright \(co 2003, 2009\-2017 Leandro A. F. Pereira \fI<leandro@hardinfo.org>\fR.
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
This manpage was created by PICCORO Lenz McKAY \fI<mckaygerhard@gmail.com>\fR for the hardinfo project.
