# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/hardinfo-2.0.12
Summary:        hardinfo2 built using CMake
Name:           hardinfo
Version:        2.0.12
Release:        1
License:        GPL2+
Group:          unknown
Vendor:         Humanity

Source: hardinfo-2.0.12.tar.gz




%define debug_package %{nil}

%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename hardinfo-2.0.12.rpm
%define _unpackaged_files_terminate_build 0





%description
Hardinfo2 - System Information and Benchmark

# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
%setup -c


%build
mkdir cpack_rpm_build_dir
cd cpack_rpm_build_dir
'/usr/bin/cmake'  ../hardinfo-2.0.12
make %{?_smp_mflags}

#p build

%install

cd cpack_rpm_build_dir
cpack -G RPM
mv *.rpm %_rpmdir

%clean

%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 2.0.12-1
  Generated by CPack RPM (no Changelog file were provided)
