#!/bin/sh
# Hardinfo2   support for root access
# chkconfig: - 99 10
# description: hardinfo2 support for root access

### BEGIN INIT INFO
# Provides: hardinfo2
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-start: 2 3 4 5
# Default-Stop:
# Short-Description: start and stop hardinfo2
# Description: hardinfo2 support for root access
### END INIT INFO


start() {
    #ADD below to allow all users access to DMI
    #chmod a+r /sys/firmware/dmi/tables/*;
   /bin/sh -c "mkdir /run/hardinfo2;cat /proc/iomem |grep -v Kernel|grep -v System >/run/hardinfo2/iomem;chmod a+r /run/hardinfo2/iomem;cat /proc/ioports >/run/hardinfo2/ioports;chmod a+r /run/hardinfo2/ioports;modprobe -q spd5118;modprobe -q ee1004;modprobe -q at24 || true"
  return 0
}

stop() {
   return 0
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status $prog
	;;
  restart|force-reload)
	stop
	start
	;;
  try-restart|condrestart)
	if status $prog > /dev/null; then
	    stop
	    start
	fi
	;;
  reload)
	exit 3
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
	exit 2
esac

exit 0
