#!/bin/sh
exec 2>&1
cat /proc/iomem >/tmp/hardinfo2_iomem
chmod a+r /tmp/hardinfo2_iomem
cat /proc/ioports >/tmp/hardinfo2_ioports
chmod a+r /tmp/hardinfo2_ioports
chmod a+r /sys/firmware/dmi/tables/*
modprobe -q spd5118
modprobe -q ee1004
modprobe -q at24
pause
